### ISSUE TITLE
Attempting to log in with an invalid password crashes the web app

### ISSUE THREAD

**Issue by broberson** [benawad/jwt-auth-example#3]
A try/catch in Login.tsx is probably needed, but that OnSubmit handler is already looking pretty heavy. What would be a sensible way to a handle GraphqlError thrown from the login mutation?

**Comment by benawad** [comment]
I think try/catch is the only way if the error is thrown

**Comment by broberson** [comment]
Nevermind this. Only works for Queries, not Mutations. Try/Catch is still necessary.

It appears that using the { errorPolicy: 'all' } option is the way to go. Whatever data you get from the server is made available, but not cached by Apollo, and the errors that occurred are made available, but nothing throws so you're free to render what you need to based on the server response. Best of both worlds.
